### PR TITLE
docs: Add palworld

### PR DESCRIPTION
**Pull request by 4s3ti**
Add palworld to supported games

I have been able to successfully use gorcon with the recently released palworld.

### CODE REVIEW

**Comment by eribbey** [comment]
@4s3ti I was unable to get connected to my Palworld dedicated server using the arm64_darwin release. Got the same error reported in issue #32 and verified that the correct port is open, as well as have active players on it. What is your YAML config / rcon command flags that you're using?

**Comment by 4s3ti** [comment]
Just the basic usage as per the readme, 

To connect to the rcon console, 

`rcon -a serveraddress:port -p password` 

or for a command:

`rcon -a serveraddress:port -p password command` 


 if you can't connect make sure you are chaning the right configuration file on palworld server. 

At least on linux chaning the `~/Steam/steamapps/common/PalServer/DefaultPalWorldSettings.ini` doesn't have anny effect, you should change the configuration file at `~/Steam/steamapps/common/PalServer/Pal/Saved/Config/LinuxServer/PalWorldSettingsi.ini`.

**Comment by BushTrocity** [comment]
Can confirm it is currently working.

**Comment by outdead** [comment]
Hi! Thanks for the request!

**Pull request merged**
